### ISSUE TITLE
Add functionality to group clusters in .i2csshrc

### ISSUE THREAD

**Issue by kevinvp** [wouterdebie/i2cssh#66]
Please add the functionality to group clusters in the .i2csshrc config.

Example:
```
---
version: 2
clusters:
  clusterA:
    hosts:
      - server1
      - server2
      - server3
  clusterB:
    hosts:
      - server4
      - server5
      - server6
  clusterC:
    hosts:
      - clusterA
      - clusterB
```
